# 检查

```{r}
# dat = melt(d, c("time"))
year <- 2020
time_beg <- make_datetime(year, 6, 1)
time_end <- make_datetime(year, 6, 24, 23)

time_beg <- make_datetime(year, 6, 12)
time_end <- time_beg + dhours(1 * 24 + 23)

dat <- cbind(d[, .(time, GPP = -GEE)], select(d, Prcp, LE, Ta = T, starts_with(c("TS", "SM")))) %>%
  .[time >= time_beg & time <= time_end]
pdat <- melt(dat, "time")

p <- ggplot(pdat, aes(time, value)) +
  geom_line() +
  scale_x_datetime(date_labels = "%m.%dH%H", minor_breaks = "3 hours") +
  facet_wrap(~variable, scales = "free") +
  vspan_day(time_beg, time_end)

input <- d[, .(time, TS_4cm_N, TS_4cm_S, SM_4cm_N, SM_4cm_S)]
data <- input[year(time) == 2020 & month(time) %in% 6]

# library(kfold)
# kfold_rf(data[, .(TS_4cm_S)], data[, .(SM_4cm_S)], ntree = 10)
write_fig(p, "d:/Rplot.pdf", 10, 5)
```

```{r}
year <- 2012
time_beg <- make_datetime(year, 8, 6)
time_end <- make_datetime(year, 8, 6 + 7, 23)

dat <- d$data[time >= time_beg & time <= time_end] # %>%
mutate(time = time + dhours(8))

p1 <- ggplot(dat, aes(time, SM)) +
  geom_line()

p2 <- ggplot(dat, aes(time, Rn)) +
  geom_line()
p3 <- ggplot(dat, aes(time, LE)) +
  geom_line()
p4 <- ggplot(dat, aes(time, Ta)) +
  geom_line()
p5 <- ggplot(dat, aes(time, Ts)) +
  geom_line()

p <- p1 / p2 / p3 / p4 / p5
write_fig(p, "d:/Rplot.pdf", 10, 8)
```
