```{r}
export_Soil <- function(lst_data) {
  outdir <- "data-raw/BEPS/SoilOBS"
  vars_need <- c("Prcp", "Ta", "LE", "Hs")
  indexes <- seq_along(lst_data) %>% set_names(names(lst_data))

  map(indexes, function(i) {
    site <- names(lst_data)[i]
    fprintf("[%d] %s \n", i, site)

    d <- lst_data[[i]] %>%
      add_time() %>%
      check_zero() %>%
      select_any(time, any_of(vars_need), starts_with(c("SM", "TS", "G_"))) %>%
      select(-any_of(starts_with(c("TS_0_", "TS_TCAV")))) %>%
      mutate(site = site, .before = 1)

    d_hour <- d[
      , c(lapply(.SD, \(x) mean(x, na.rm = TRUE)), .N),
      .(site, time = floor_date(time, "hour"))
    ] %>%
      mutate(Prcp = Prcp * N) %>%
      select(-N) # Prcp 是累积量

    d_day <- d_hour[
      , c(lapply(.SD, \(x) mean(x, na.rm = TRUE)), .N),
      .(site, time = floor_date(time, "day"))
    ] %>%
      mutate(Prcp = Prcp * N) %>%
      select(-N) # Prcp 是累积量

    fout <- glue("{outdir}/{site}_SM&TS_hourly.csv")
    fwrite(d_hour, fout, bom = TRUE)

    fout_day <- glue("{outdir}/daily/{site}_SM&TS_daily.csv")
    fwrite(d_day, fout_day, bom = TRUE)

    d_day
  })
}

res <- export_Soil(lst_data)
```

## summary

```{r}
map(seq_along(lst_data), function(i) {
  site <- names(lst_data)[i]
  fprintf("[%d] %s \n", i, site)
  d <- lst_data[[i]] %>%
    select_any(starts_with(c("SM")))
  summary(d)
})
```
