```{r}
# fmt: skip
pacman::p_load(
  Ipaper, data.table, dplyr, lubridate,
  ggplot2, gg.layers, patchwork
)

devtools::load_all(".")
outdir = "data-raw/Hourly"

guess_fout <- function(f_met, outdir) {
  sprintf("%s/%s", outdir, gsub("Met", "FluxMet", basename(f_met)))
}

read_fluxmet <- function(f_met) {
  f_flux <- gsub("Met", "Flux", f_met)
  met <- read_ufile(f_met)
  flux <- read_ufile(f_flux)
  l <- merge_ufile(flux, met)
  l
}
```

## 1 临泽
```{r}
f_met = "data-raw/ALL/ChinaFlux_CRO_临泽_2012-2015/临泽_30min_Met_2012_2015.csv"
l <- read_fluxmet(f_met)
l$data %<>% mutate(
  across(Ta:TS_10cm, \(x) as.numeric(x)),
  SM_10cm = SM_10cm * 100
) # %>% rename(TS_10cm = Ts, SM_10cm = SM)
l$data[SM_10cm == 0, SM_10cm := NA_real_] %>% invisible()
l$data[TS_10cm > 100, TS_10cm := NA_real_] %>% invisible()

# fout <- guess_fout(f_met, outdir)
fout = "data-raw/Hourly/CRO_临泽_30min_FluxMet_2012_2015.csv"
write_ufile(l, fout)
# f_met = "data-raw/ALL/ChinaFlux_CRO_临泽_2012-2015/临泽_30min_Met_2012_2015.csv"
# l <- read_fluxmet(f_met)
```

## 2 固城

```{r}
f_met = "data-raw/ALL/ChinaFlux_CRO_固城_冬小麦夏玉米_2020-2022/固城_Met_30min_2020_2022.csv"
l <- read_fluxmet(f_met)

var_replacement = c(
  "_probe_Avg" = "",
  "_Avg|_meas" = "",
  "Precipitation_Tot" = "Prcp",
  "Soil_T_" = "TS_4cm_",
  "Soil_VWC_" = "SM_4cm_"
)

l2 <- map_ufile(l, \(d) {
  add_time(d) %>%
    select(-starts_with(c("QC", "WD"))) %>%
    rename_vars(var_replacement)
})
l2$data[albedo > 100, albedo := albedo / 1000] %>% invisible()

fout = guess_fout(f_met, outdir)
fout = "data-raw/Hourly/CRO_冬小麦夏玉米_固城_30min_FluxMet_2020_2022.csv"
write_ufile(l2, fout)
```

## 3 禹城

```{r}
f_met = "data-raw/ALL/ChinaFlux_CRO_禹城_2003-2010/禹城_Met_30min_2003_2010.csv"
l <- read_fluxmet(f_met)

l2 <- map_ufile(l, \(d) {
  add_time(d) %>%
    select(-starts_with(c("QC", "WD"))) %>%
    rename_vars(var_replacement)
})
l2$data %<>% mutate(across(2:last_col(), as.numeric))

fout = "data-raw/Hourly/CRO_冬小麦夏玉米_禹城_30min_FluxMet_2020_2022.csv"
write_ufile(l2, fout)
```

## 4 CRO 盘锦 稻田
> [bug]
```{r}
f_met = "data-raw/ALL/ChinaFlux_CRO_盘锦_稻田-2018-2020/盘锦-稻田站_Met_30min_2018-2020.csv"

f_flux <- gsub("Met", "Flux", f_met)
met <- read_ufile(f_met)
met$data %<>% mutate(date = date + dhours(hour(time)) + dminutes(minute(time))) %>%
  select(-time)
met$unit %<>% select(-time)

flux <- read_ufile(f_flux)
flux$data %<>% mutate(date = ymd_hm(paste0(date, " ", time))) %>% select(-time)
flux$unit %<>% select(-time)

l <- merge_ufile(flux, met)
# l <- read_fluxmet(f_met)

fout = "data-raw/Hourly/CRO_水稻_盘锦_30min_FluxMet_2018_2020.csv"
write_ufile(l, fout)
```

## 5 CRO 锦州 春玉米

```{r}
f_met = "data-raw/ALL/ChinaFlux_CRO_锦州_2005-2014/锦州_Met_30min_2005_2014.csv"
l <- read_fluxmet(f_met)

fout = "data-raw/Hourly/CRO_春玉米_锦州_30min_FluxMet_2005_2014.csv"
write_ufile(l, fout)
```

## CRO 长岭 水稻（东北）
```{r}
f_met = "data-raw/ALL/ChinaFlux_CRO_长岭_稻田_2020/长岭_水稻_Met_30min_2018-2020.csv"
l <- read_fluxmet(f_met)

fout <- "data-raw/Hourly/CRO_水稻_长岭_30min_FluxMet_2018_2020.csv"
write_ufile(l, fout)
```
