```{r}
pacman::p_load(Ipaper, data.table, dplyr, lubridate)
devtools::load_all(".")
dir_root = "data-raw/ChinaFlux_ENF_千烟洲_人工针叶林_2003-2010"
```

```{r}
fs_flux = dir2("data-raw/ChinaFlux_ENF_千烟洲_人工针叶林_2003-2010/raw/Flux/30min")
df_flux = read_files(fs_flux) %>% rbindlist() %>% unique()
fwrite(df_flux, "data-raw/ChinaFlux_ENF_千烟洲_人工针叶林_2003-2010/30min/千烟洲_Flux_30min_2011_2015.csv")

fs_met = dir2("data-raw/ChinaFlux_ENF_千烟洲_人工针叶林_2003-2010/raw/Met/30min")
df_met = read_files(fs_met) %>% rbindlist() %>% unique()
fwrite(df_met, "data-raw/ChinaFlux_ENF_千烟洲_人工针叶林_2003-2010/30min/千烟洲_Met_30min_2011_2015.csv")
```

## 2003-2010

```{r}
vars = c("年,月,日,时,分,秒,近地面空气温度,冠层上方空气温度,近地面空气湿度,冠层上方空气湿度,近地面水汽压,冠层上方水汽压,近地面风速,冠层上方风速,风向,大气压,太阳辐射,净辐射,光合有效辐射,一层土壤温度,二层土壤温度,三层土壤温度,四层土壤温度,五层土壤温度,一层土壤体积含水量,二层土壤体积含水量,三层土壤体积含水量,降水量") %>% split_vars()

fwrite_glue(vars, "{dir_root}/VarNames_Met_2003-2010.csv", col.names = FALSE)
```

```{r}
vars = "年,月,日,时,分,近地面空气温度,冠层上方空气温度,近地面空气相对湿度,冠层上方空气相对湿度,近地面水汽压,冠层上方水汽压,近地面风速,冠层上方风速,风向,大气压,太阳辐射,净辐射,光合有效辐射,一层土壤温度,二层土壤温度,三层土壤温度,一层土壤体积含水量,二层土壤体积含水量,三层土壤体积含水量,降水量" %>% split_vars()
fwrite_glue(vars, "{dir_root}/VarNames_Met_2011-2015.csv", col.names = FALSE)
```


## 合并met

```{r}
f1 = "{dir_root}/30min/backup/千烟洲_Met_30min_2003_2010.csv"
f2 = "{dir_root}/30min/backup/千烟洲_Met_30min_2011_2015.csv"

f_var1 = "{dir_root}/VarNames_Met_2003-2010.csv"
f_var2 = "{dir_root}/VarNames_Met_2011-2015.csv"

d1 = patch_names(f1, f_var1)
d2 = patch_names(f2, f_var2)
d = rbind(d1, d2, fill = TRUE) %>% unique()
fwrite_glue(d, "{dir_root}/30min/千烟洲_Met_30min_2003_2015.csv")
```

## 合并Flux

```{r}
d1 <- fread_glue("{dir_root}/30min/千烟洲_Flux_30min_2003_2010.csv")
d2 <- fread_glue("{dir_root}/30min/千烟洲_Flux_30min_2011_2015.csv")
d_flux = rbind(d1, d2) %>% unique()

fwrite_glue(d_flux, "{dir_root}/30min/千烟洲_Flux_30min_2003_2015.csv")
```

## 合并met和flux

```{r}
d_flux= fread_glue("{dir_root}/30min/千烟洲_Flux_30min_2003_2015.csv")
d_met = fread_glue("{dir_root}/30min/千烟洲_Met_30min_2003_2015.csv")

by = intersect(names(d_flux), VARS_DATE)
d = merge(d_flux, d_met, by, all = TRUE) %>% unique()

fwrite_glue(d, "{dir_root}/30min/千烟洲_FluxMet_30min_2003_2015.csv")
fwrite_glue(d, "data-raw/0_Hourly/ENF_千烟洲_人工针叶林_30min_FluxMet_2003_2015.csv")
```
