```{r}
pacman::p_load(Ipaper, data.table, dplyr, lubridate, stringr, zeallot)
devtools::load_all(".")

```

## CRO

```{r}
dir_root = "data-raw/ALL/ChinaFlux_CRO_临泽_2012-2015/"
f_met = find_met_day(dir_root)

SITE <- "临泽"
VegType <- "CRO"
VegName <- "制种玉米"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
# %% 2 固城
dir_root = "data-raw/ALL/ChinaFlux_CRO_固城_冬小麦夏玉米_2020-2022/"
f_met = find_met_day(dir_root)
SITE <- "固城"
VegType <- "CRO"
VegName <- "冬小麦夏玉米"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
# %% 3 禹城
dir_root = "data-raw/ALL/ChinaFlux_CRO_禹城_2003-2010/"
f_met = find_met_day(dir_root)

SITE <- "禹城"
VegType <- "CRO"
VegName <- "冬小麦夏玉米"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
# %% 4 CRO 盘锦 稻田
dir_root = "data-raw/ALL/ChinaFlux_CRO_盘锦_稻田-2018-2020/"
f_met = find_met_day(dir_root)

SITE <- "盘锦"
VegType <- "CRO"
VegName <- "水稻"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
# %% 5 CRO 锦州 春玉米
dir_root = "data-raw/ALL/ChinaFlux_CRO_锦州_2005-2014/"
f_met = find_met_day(dir_root)

SITE <- "锦州"
VegType <- "CRO"
VegName <- "春玉米"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
# %% CRO 长岭 水稻（东北）
dir_root = "data-raw/ALL/ChinaFlux_CRO_长岭_稻田_2020/"
f_met = find_met_day(dir_root)

SITE <- "长岭"
VegType <- "CRO"
VegName <- "水稻"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```


## EBF （5个站点）

```{r}
dir_root = "data-raw/ALL/ChinaFlux_EBF_哀牢山_EBF-2009-2013/"
f_met = find_met_day(dir_root)

SITE = "哀牢山"
VegType = "EBF"
VegName = "亚热带常绿阔叶林"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/ChinaFlux_EBF_海南儋州-橡胶林_2010-2018/"
f_met = "{dir_root}/儋州橡胶林_Met_数据_Day_2010_2018.csv" %>% glue()

SITE = "海南儋州"
VegType = "EBF"
VegName = "橡胶林"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/ChinaFlux_EBF_西双版纳-橡胶林_2010-2014/"
f_met = find_met_day(dir_root)

SITE = "西双版纳"
VegType = "EBF"
VegName = "橡胶林"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/ChinaFlux_EBF_西双版纳_热带雨林_2003-2015/"
f_met = find_met_day(dir_root)

SITE = "西双版纳"
VegType = "EBF"
VegName = "热带雨林"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/EBF_金佛山_2020-2021/"
# code(dir_root)
f_met = find_met_day(dir_root)

SITE = "金佛山"
VegType = "EBF"
VegName = "亚热带常绿阔叶林"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

## DBF

```{r}
dir_root = "data-raw/ALL/ChinaFlux_DBF_帽儿山_DBF-2016-2018/"
f_met = find_met_day(dir_root)

SITE = "帽儿山"
VegType = "DBF"
VegName = "温带落叶阔叶林"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

## ENF

```{r}
f_met = "data-raw/ALL/ChinaFlux_ENF_千烟洲_人工针叶林_2003-2010/千烟洲_Met_Day_2003-2015.csv"

SITE = "千烟洲"
VegType = "ENF"
VegName = "人工针叶林"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/ENF_呼中_北方林森林_2014-2018"
# code(dir_root)
f_met = find_met_day(dir_root)

SITE = "呼中"
VegType = "ENF"
VegName = "北方林森林"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

> 燕山
```{r}
f_met = "data-raw/ALL/燕山-山地丘陵区_2020-2021/燕山灌丛_Met_日_2020_2021.csv" # 共用一个met
# code(dirname(f_met))
SITE = "燕山"

VegType = "WSA"
VegName = "灌丛" # 山地灌丛, 荆条 + 扁担杆
# z_canopy = 1.7
f_flux = "data-raw/ALL/燕山-山地丘陵区_2020-2021/燕山灌丛_Flux_日_2020_2021.csv" # z_tower = 30m
merge_daily_FluxMet(f_met, SITE, VegType, VegName, f_flux = f_flux)

VegType = "MF"
VegName = "乔灌混交林" # 油松 + 荆条
# z_canopy = 1.7 ~ 11
f_flux = "data-raw/ALL/燕山-山地丘陵区_2020-2021/燕山乔灌混交林_Flux_日_2020_2021.csv" # z_tower = 15m
merge_daily_FluxMet(f_met, SITE, VegType, VegName, f_flux = f_flux)

VegType = "ENF"
VegName = "人工针叶林" # 油松 + 侧柏
# z_canopy = 8 ~ 11
f_flux = "data-raw/ALL/燕山-山地丘陵区_2020-2021/燕山人工针叶林_Flux_日_2020_2021.csv" # z_tower = 20m
merge_daily_FluxMet(f_met, SITE, VegType, VegName, f_flux = f_flux)
```

## MF
```{r}
dir_root = "data-raw/ALL/ChinaFlux_MF_鼎湖山_针阔叶混交林_2003-2010/"
f_met = find_met_day(dir_root)
SITE = "鼎湖山"
VegType = "MF"
VegName = "针阔混交"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
# 温带原始针阔叶混交林
dir_root = "data-raw/ALL/ChinaFlux_MF_长白山_阔叶红松林_2003-2010/"
# code(dir_root)
f_met = find_met_day(dir_root)
SITE = "长白山"
VegType = "MF"
VegName = "针阔混交"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

## DBF
```{r}
dir_root = "data-raw/ALL/DBF_宝天曼_天然栎林_2017-2018/"
f_met = find_met_day(dir_root)

SITE = "宝天曼"
VegType = "DBF"
VegName = "天然栎林"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/DBF_小浪底_栓皮栎人工林_2016-2017/"
f_met = find_met_day(dir_root)

SITE = "小浪底"
VegType = "DBF"
VegName = "栓皮栎人工林"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

## GRA
```{r}
dir_root = "data-raw/ALL/ChinaFlux_GRA_当雄_高寒草甸_2004-2010/"
f_met = find_met_day(dir_root)
SITE = "当雄"
VegType = "GRA"
VegName = "高寒草甸"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/ChinaFlux_GRA_海北_2015-2020_高寒草甸/"
f_met = find_met_day(dir_root)

SITE = "海北"
VegType = "GRA"
VegName = "高寒草甸"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/GRA_内蒙-锡林浩特_刈割草原_2006-2015/"
f_met = find_met_day(dir_root)

SITE = "锡林浩特"
VegType = "GRA"
VegName = "刈割草原"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/ChinaFlux_GRA_内蒙-锡林浩特-典型草原_2003-2010年/"
f_met = find_met_day(dir_root)

SITE = "锡林浩特"
VegType = "GRA"
VegName = "典型草原"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/ChinaFlux_GRA_三江源-垂穗披碱草_2012-2016/"
f_met = find_met_day(dir_root)

SITE = "三江源"
VegType = "GRA"
VegName = "人工垂穗披碱草"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/ChinaFlux_GRA_若尔盖-高寒草甸_2015-2020"
f_met = find_met_day(dir_root)
SITE = "若尔盖"
VegType = "GRA"
VegName = "高寒草甸"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/GRA_那曲_高寒草甸_2014-2018"
f_met = find_met_day(dir_root)

SITE = "那曲"
VegType = "GRA"
VegName = "高寒草甸"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

## 其他
> WSA
```{r}
dir_root = "data-raw/ALL/ChinaFlux_WSA_海北_高寒灌丛_2011-2020/"
f_met = find_met_day(dir_root)

SITE = "海北"
VegType = "WSA"
VegName = "高寒灌丛"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
f_met = "data-raw/ALL/WET_海北_高寒湿地-2004-2009/海北湿地_Met_日_2003_2010.csv"
f_flux = "data-raw/ALL/WET_海北_高寒湿地-2004-2009/海北湿地_Flux_日_2004_2009.csv"

SITE = "海北"
VegType = "WET"
VegName = "高寒湿地"
merge_daily_FluxMet(f_met, SITE, VegType, VegName, f_flux = f_flux)
```

```{r}
dir_root = "data-raw/ALL/ChinaFlux_GRA_元江-干热河谷_稀树草原_2013-2015"
f_met = find_met_day(dir_root)

SITE = "元江"
VegType = "GRA"
VegName = "稀树草原"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/GRA_内蒙-多伦_2006-2015"
f_met = find_met_day(dir_root)
# code(dir_root)

SITE = "多伦"
VegType = "GRA"
VegName = "典型草原"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

##

1	达茂	SAV（荒漠草原）	2015-2018
2	崇明东滩	WET（湿地）	2004-2010
3	洞庭湖	WET（南荻）	2014-2016
4	海北	WET（高寒湿地）	2004-2009
5	盘锦	WET（芦苇湿地）	2018-2020
6	普定	WSA（退耕还林）	2015-2019

```{r}
## 该站点不需要处理
dir_root = "data-raw/ALL/SAV_荒漠草原_达茂_2015-2018/"
f_met = find_met_day(dir_root)
# SITE = "达茂"
# VegType = "SAV"
# VegName = "荒漠草原"
# merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
# 该站点不需要处理
dir_root = "data-raw/ALL/WET_崇明东滩_湿地-2004-2010"
f_met = find_met_day(dir_root)
```

```{r}
dir_root = "data-raw/ALL/WET_洞庭湖-南荻_2014-2016/"
f_met = find_met_day(dir_root)
SITE = "洞庭湖"
VegType = "WET"
VegName = "南荻湿地"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/WET_海北_高寒湿地-2004-2009/"
f_met = glue("{dir_root}/海北湿地_Met_日_2003_2010.csv")

SITE = "海北"
VegType = "WET"
VegName = "高寒湿地"
f_flux = glue("{dir_root}/海北湿地_Flux_日_2004_2009.csv")
merge_daily_FluxMet(f_met, SITE, VegType, VegName, f_flux = f_flux)
```

```{r}
dir_root = "data-raw/ALL/WET_芦苇湿地_盘锦-2018-2020/"
f_met = find_met_day(dir_root)

SITE = "盘锦"
VegType = "WET"
VegName = "芦苇湿地"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/普定-退耕还林_2015-2019/"
f_met = find_met_day(dir_root)
SITE = "普定"
VegType = "WSA"
VegName = "退耕还林"
merge_daily_FluxMet(f_met, SITE, VegType, VegName)
```

---

- `句容`
- `栾城`
- `庆阳`
