```{r}
pacman::p_load(Ipaper, data.table, dplyr, lubridate, stringr, zeallot)
devtools::load_all(".")
outdir = "data-raw/Hourly"
```

## CRO

```{r}
# %% 1 临泽
f_met <- "data-raw/ALL/CRO_制种玉米_临泽_2012-2015/临泽_30min_Met_2012_2015.csv"
SITE <- "临泽"
VegType <- "CRO"
VegName <- "制种玉米"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
# l$data[SM_10cm == 0, SM_10cm := NA_real_] %>% invisible()
# l$data[TS_10cm > 100, TS_10cm := NA_real_] %>% invisible()
```

```{r}
# %% 2 固城
# l2$data[albedo > 100, albedo := albedo / 1000] %>% invisible()
f_met <- "data-raw/ALL/CRO_冬小麦夏玉米_固城_2020-2022/固城_Met_30min_2020_2022.csv"
SITE <- "固城"
VegType <- "CRO"
VegName <- "冬小麦夏玉米"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
# %% 3 禹城
f_met <- "data-raw/ALL/CRO_冬小麦夏玉米_禹城_2003-2010/禹城_Met_30min_2003_2010.csv"
SITE <- "禹城"
VegType <- "CRO"
VegName <- "冬小麦夏玉米"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
# %% 4 CRO 盘锦 稻田
f_met <- "data-raw/ALL/CRO_水稻_盘锦-2018-2020/盘锦-稻田站_Met_30min_2018-2020.csv"
SITE <- "盘锦"
VegType <- "CRO"
VegName <- "水稻"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
# %% 5 CRO 锦州 春玉米
f_met <- "data-raw/ALL/CRO_春玉米_锦州_2005-2014/锦州_Met_30min_2005_2014.csv"
# code(dirname(f_met))
SITE <- "锦州"
VegType <- "CRO"
VegName <- "春玉米"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
# %% CRO 长岭 水稻（东北）
f_met <- "data-raw/ALL/CRO_水稻_长岭_2018-2020/长岭_水稻_Met_30min_2018-2020.csv"
SITE <- "长岭"
VegType <- "CRO"
VegName <- "水稻"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

## EBF （5个站点）

```{r}
dir_root = "data-raw/ALL/EBF_常绿阔叶_哀牢山_EBF-2009-2013/"
f_met = dir2(dir_root, "_Met_30min")

SITE = "哀牢山"
VegType = "EBF"
VegName = "亚热带常绿阔叶林"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/EBF_橡胶林_海南儋州_2010-2018/"
# code(dir_root)
f_met = "{dir_root}/儋州橡胶林_Met_数据（30分钟）_2010_2018.csv" %>% glue()

SITE = "海南儋州"
VegType = "EBF"
VegName = "橡胶林"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/EBF_橡胶林_西双版纳_2010-2014/"
f_met = dir2(dir_root, "_Met_30min")

SITE = "西双版纳"
VegType = "EBF"
VegName = "橡胶林"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/EBF_热带雨林_西双版纳_2003-2015/"
f_met = dir2(dir_root, "_Met_30min")
SITE = "西双版纳"
VegType = "EBF"
VegName = "热带雨林"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/EBF_常绿阔叶_金佛山_2020-2021/"
# code(dir_root)
f_met = "{dir_root}/金佛山-亚热带-EBF_Hour_Met_2020_2021.csv" %>% glue()

SITE = "金佛山"
VegType = "EBF"
VegName = "亚热带常绿阔叶林"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

## DBF

```{r}
dir_root = "data-raw/ALL/DBF_落叶阔叶_帽儿山_DBF-2016-2018/"
dir(dir_root, "30min")[2]
# code(dir_root)

SITE = "帽儿山"
VegType = "DBF"
VegName = "温带落叶阔叶林"
f_met = glue("{dir_root}/帽儿山站_DBF_Met_30min数据_2016_2018.csv")
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

## ENF

```{r}
f_met = "data-raw/ALL/ENF_人工针叶林_千烟洲_2003-2010/千烟洲_Met_30min_2003_2015.csv"

SITE = "千烟洲"
VegType = "ENF"
VegName = "人工针叶林"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/ENF_北方林森林_呼中_2014-2018"
# code(dir_root)
f_met = dir2(dir_root, "_Met_30min")
SITE = "呼中"
VegType = "ENF"
VegName = "北方林森林"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

> 燕山
```{r}
f_met = "data-raw/ALL/燕山-山地丘陵区_2020-2021/燕山灌丛_Met_30min_2020_2021.csv" # 共用一个met
# code(dirname(f_met))
SITE = "燕山"

VegType = "WSA"
VegName = "灌丛" # 山地灌丛, 荆条 + 扁担杆
# z_canopy = 1.7
f_flux = "data-raw/ALL/燕山-山地丘陵区_2020-2021/燕山灌丛_Flux_30min_2020_2021.csv" # z_tower = 30m
merge_hourly_FluxMet(f_met, SITE, VegType, VegName, f_flux = f_flux)

VegType = "MF"
VegName = "乔灌混交林" # 油松 + 荆条
# z_canopy = 1.7 ~ 11
f_flux = "data-raw/ALL/燕山-山地丘陵区_2020-2021/燕山乔灌混交林_Flux_30min_2020_2021.csv" # z_tower = 15m
merge_hourly_FluxMet(f_met, SITE, VegType, VegName, f_flux = f_flux)

VegType = "ENF"
VegName = "人工针叶林" # 油松 + 侧柏
# z_canopy = 8 ~ 11
f_flux = "data-raw/ALL/燕山-山地丘陵区_2020-2021/燕山人工针叶林_Flux_30min_2020_2021.csv" # z_tower = 20m
merge_hourly_FluxMet(f_met, SITE, VegType, VegName, f_flux = f_flux)
```

## MF
```{r}
dir_root = "data-raw/ALL/MF_针阔叶混交_鼎湖山_2003-2010/"
f_met = dir2(dir_root, "_Met_30min")
SITE = "鼎湖山"
VegType = "MF"
VegName = "针阔混交"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
# 温带原始针阔叶混交林
dir_root = "data-raw/ALL/MF_阔叶红松林_长白山_2003-2010/"
# code(dir_root)

f_met = dir2(dir_root, "_Met_30min")
SITE = "长白山"
VegType = "MF"
VegName = "针阔混交"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

## DBF
```{r}
dir_root = "data-raw/ALL/DBF_天然栎林_宝天曼_2017-2018/"
f_met = dir2(dir_root, "_Met_30min")
SITE = "宝天曼"
VegType = "DBF"
VegName = "天然栎林"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/DBF_栓皮栎人工林_小浪底_2016-2017/"
f_met = dir2(dir_root, "_Met_30min")
SITE = "小浪底"
VegType = "DBF"
VegName = "栓皮栎人工林"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

## GRA
```{r}
dir_root = "data-raw/ALL/GRA_高寒草甸_当雄_2004-2010/"
f_met = dir2(dir_root, "_Met_30min")
SITE = "当雄"
VegType = "GRA"
VegName = "高寒草甸"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/GRA_高寒草甸_海北_2015-2020/"
f_met = dir2(dir_root, "_Met_30min")

SITE = "海北"
VegType = "GRA"
VegName = "高寒草甸"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
f_met = "data-raw/ALL/GRA_刈割草原_锡林浩特_2006-2015/锡林浩特_Hour_Met_2006-2015.csv"
SITE = "锡林浩特"
VegType = "GRA"
VegName = "刈割草原"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
f_met = "data-raw/ALL/GRA_典型草原_锡林浩特_2003-2010年/内蒙古_Met_30min_2003_2010.csv"
SITE = "锡林浩特"
VegType = "GRA"
VegName = "典型草原"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
f_met = "data-raw/ALL/GRA_垂穗披碱草_三江源_2012-2016/三江源垂穗披-碱草人工草地_Met_30min_2012_2016.csv"
SITE = "三江源"
VegType = "GRA"
VegName = "人工垂穗披碱草"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
dir_root = "data-raw/ALL/GRA_高寒草甸_若尔盖_2015-2020"
f_met = dir2(dir_root, "_Met_30min.*.csv")
SITE = "若尔盖"
VegType = "GRA"
VegName = "高寒草甸"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
f_met = "data-raw/ALL/GRA_高寒草甸_那曲_2014-2018/GRA_那曲_高寒草甸_2014-2018_30min_Met.csv"
SITE = "那曲"
VegType = "GRA"
VegName = "高寒草甸"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

## 其他
> WSA
```{r}
f_met = "data-raw/ALL/WSA_高寒灌丛_海北_2011-2020/海北_Met_30min_2011-2020.csv"
SITE = "海北"
VegType = "WSA"
VegName = "高寒灌丛"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
f_met = "data-raw/ALL/WET_高寒湿地_海北-2004-2009/海北湿地_Met_30min_2003_2010.csv"
f_flux = "data-raw/ALL/WET_高寒湿地_海北-2004-2009/海北湿地_Flux_30min_2004_2009.csv"

SITE = "海北"
VegType = "WET"
VegName = "高寒湿地"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName, f_flux = f_flux)
```

```{r}
f_met = "data-raw/ALL/GRA_稀树草原_元江_2013-2015/元江站_Met_30min_2013_2015.csv"
SITE = "元江"
VegType = "GRA"
VegName = "稀树草原"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```

```{r}
f_met = "data-raw/ALL/GRA_典型草原_多伦_2006-2015/多伦_Hour_Met_2006-2015.csv"
SITE = "多伦"
VegType = "GRA"
VegName = "典型草原"
merge_hourly_FluxMet(f_met, SITE, VegType, VegName)
```
