```{r}
pacman::p_load(
  Ipaper, data.table, dplyr, lubridate,
  jsonlite, stringr,
  ggplot2, gg.layers, patchwork
)

str_site <- function(f) {
  str_extract(basename(f), ".*(?=_30min)")
}

tidy_unit <- function(d) {
  data.table(
    name = names(d), name_new = NA_character_,
    unit = unlist(d), unit_new = NA_character_, comment = ""
  )
}
```

# PART1
```{r}
fs <- dir2("data-raw/Hourly/", "*.csv")
sites <- str_site(fs)
names(fs) <- sites

lst <- map(fs, \(f) read_ufile(f, nrows = 10))
lst_unit <- map(lst, "unit")

sites_bad <- c("DBF_温带落叶阔叶林_帽儿山", "EBF_亚热带常绿阔叶林_哀牢山")
inds_bad <- match(sites_bad, sites)
inds <- grep("EBF|ENF|MF|DBF", sites) %>% setdiff(inds_bad)

write_json(lst_unit[inds], "data/Unit/ChinaFlux_Variable_Info_Forest_Hourly.json", pretty = TRUE)
# write_json(info, "./ChinaFlux_Variable_Info_Hourly.json", pretty = TRUE)
# write_json(info[inds], "./ChinaFlux_Variable_Info_Forest_Hourly.json", pretty = TRUE)
```

> 检查变量是否齐全
```{r, eval = FALSE}
# res = map(lst_unit[inds], tidy_unit)
# r = melt_list(res, "site")
# fwrite(r, "data/Unit/ChinaFlux_Variable_Info_Forest_Hourly.csv", bom = TRUE)
# # write_list2xlsx(list(unit = r), "data/Unit/ChinaFlux_Variable_Info_Forest_Hourly.xlsx")
# # write_json(res, "./ChinaFlux_Variable_Info_Forest_Hourly.json", pretty = TRUE)

# vars_need = c("Ta_canopy", "RH_canopy", "WS_canopy", "Rs", "Rln_in", "Prcp")
# # vars_need = c("Ta", "WS", "Rs_out", "Rln_out")
# res = lst_unit[inds] %>% map(function(d) {
#   select(d, any_of(vars_need))
# })

# nvar = sapply(res, ncol)
# table(nvar)
# # res[nvar == 1]
# # res[nvar == 3]
# # res[nvar == 4]
```


# PART2 数据保存

```{r}
# %% 1. Met
lst <- map(fs[inds], \(f) read_ufile(f, nrows = Inf))
# lst_unit <- map(lst, "unit")
# lst_data <- map(lst, "data")
```

```{r}
lst2 <- map(lst, unify_unit_hourly)
lst_unit <- map(lst2, "unit")
lst_data <- map(lst2, "data")
write_json(lst_unit, "data/Unit/ChinaFlux_Variable_Info_Forest_Hourly.json", pretty = TRUE)
```

```{r}
# 在这里需要进行单位一致性核验
```

## Met hourly

```{r}
vars_need <- c("Ta_canopy", "RH_canopy", "WS_canopy", "Rs", "Rln_in", "Prcp")

res <- map(seq_along(lst_data), function(i) {
  site <- names(lst_data)[i]
  print(site)

  d <- lst_data[[i]] %>%
    add_time() %>%
    select_any(time, any_of(vars_need)) %>%
    mutate(site = site, .before = 1)
  # 30min to hourly
  d_hour = d[, c(lapply(.SD, \(x) mean(x, na.rm = TRUE)), .N), 
    .(site, time = floor_date(time, "hour"))] %>% 
    mutate(Prcp = Prcp * N) %>% select(-N) # Prcp是累积

  # d_hour[, .N, .(site, time)][N > 1]
  d_hour[is.na(Prcp), Prcp := 0.0]
  d_hour = d_hour %>% mutate(across(-c(site, time, Prcp, Rln_in), \(x) na_interp(time, x)))
  arrange(d_hour, time)
})

df <- rbindlist(res)
# summary(df)
fwrite(df, "data-raw/BEPS/Forcing_Met_Hourly_BEPS_Forest_sp12_hourly_v20260507.csv", bom = TRUE)
```

## 土壤 hourly

```{r}
check_SM <- function(d) {
  mutate(d, across(starts_with("SM"), \(x) {
    x[x <= 0 | x > 1] <- NA_real_
    x
  }))
}
```

```{r}
export_Soil <- function(lst_data) {
  outdir <- "data-raw/BEPS/SoilOBS"
  vars_need <- c("Prcp", "Ta", "LE", "Hs")
  indexes <- seq_along(lst_data) %>% set_names(names(lst_data))

  map(indexes, function(i) {
    site <- names(lst_data)[i]
    print(site)
    d <- lst_data[[i]] %>%
      add_time() %>% 
      check_SM() %>% 
      select_any(time, any_of(vars_need), starts_with(c("SM", "TS", "G_"))) %>%
      select(-any_of(starts_with(c("TS_0", "TS_TCAV")))) %>%
      mutate(site = site, .before = 1)
    
    d_hour = d[, c(lapply(.SD, \(x) mean(x, na.rm = TRUE)), .N), 
      .(site, time = floor_date(time, "hour"))] %>% 
      mutate(Prcp = Prcp * N) %>% select(-N) # Prcp是累积

    # fwrite(d, glue("{outdir}/{site}_SM&TS_30min.csv"), bom = TRUE)
    fout = glue("{outdir}/{site}_SM&TS_hourly.csv")
    fwrite(d_hour, fout, bom = TRUE)

    # dat <- melt(d, c("site", "time"))
    dat <- melt(d_hour, c("site", "time"))
    p <- ggplot(dat, aes(time, value)) +
      geom_line() +
      facet_wrap(~variable, scales = "free") +
      theme_bw()
    write_fig(p, gsub(".csv", ".pdf", fout), 14, 7, show = FALSE)
    d_hour
  })
}

res = export_Soil(lst_data)
# system.time({
#   write_list2xlsx(res, "data-raw/BEPS/Forcing_SM&TS_Hourly_BEPS_Forest_sp12_V2.xlsx")
# })
```


## Flux hourly
```{r}
df <- fread(
  "Z:/Researches/ET_ModelDev/data-raw/Flux/Flux_PART1_ChinaFlux_tidied_Daily_2003-2022_st39_v20260403.csv"
)
st_full <- fread("data/st_flux39_names.csv")
st <- st_full[site %in% names(lst_data)]

df_flux <- df[name %in% st$name, ] %>%
  mutate(site = factor(name, st$name, st$site))
fwrite(df_flux, "data-raw/BEPS/Forcing_Flux_Daily_BEPS_Forest_sp12.csv")

# %% 3. lai
lst_LAI <- readRDS("data-raw/BEPS/LAI/ALL_LAI_GLASS&WHIT_1D_2000-2024_st341.rds")
df_LAI <- lst_LAI[st$site_old] %>%
  set_names(st$site) %>%
  melt_list("site")
fwrite(df_LAI, "data-raw/BEPS/Forcing_LAI_Daily_BEPS_Forest_sp12_v20260506.csv", bom = TRUE)
```
